#! /bin/bash

# Defaults
LIBTOOL=libtool
LIBTOOLIZE=libtoolize

# Fix OSx problem with GNU libtool
(uname -a|grep -v Darwin) < /dev/null > /dev/null 2>&1 ||
{
    echo "....Adding fix for OSX"
        LIBTOOL=glibtool
        LIBTOOLIZE=glibtoolize
}

autoreconf -fvi
